development: &development
  adapter: postgresql
  database: reunionpong_development

staging:
  <<: *development

production:
  <<: *development

test: &test
  adapter: postgresql
  database: reunionpong_test
  min_messages: warning


cucumber:
  <<: *test


